// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.15.5
// source: proto/acts.proto

package acts_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// subscript message options
type MessageOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// message type
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// message event
	State string `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	// model tag
	Tag string `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
	// message key
	Key string `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`
	// message uses
	Uses string `protobuf:"bytes,6,opt,name=uses,proto3" json:"uses,omitempty"`
}

func (x *MessageOptions) Reset() {
	*x = MessageOptions{}
	mi := &file_proto_acts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOptions) ProtoMessage() {}

func (x *MessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOptions.ProtoReflect.Descriptor instead.
func (*MessageOptions) Descriptor() ([]byte, []int) {
	return file_proto_acts_proto_rawDescGZIP(), []int{0}
}

func (x *MessageOptions) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *MessageOptions) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MessageOptions) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *MessageOptions) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *MessageOptions) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// grpc message with server or client
type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Seq  string  `protobuf:"bytes,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Ack  *string `protobuf:"bytes,3,opt,name=ack,proto3,oneof" json:"ack,omitempty"`
	Data []byte  `protobuf:"bytes,4,opt,name=data,proto3,oneof" json:"data,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_acts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_acts_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Message) GetSeq() string {
	if x != nil {
		return x.Seq
	}
	return ""
}

func (x *Message) GetAck() string {
	if x != nil && x.Ack != nil {
		return *x.Ack
	}
	return ""
}

func (x *Message) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_acts_proto protoreflect.FileDescriptor

var file_proto_acts_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x09, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x22, 0x7b, 0x0a,
	0x0e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x70, 0x0a, 0x07, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x15, 0x0a, 0x03, 0x61,
	0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x61, 0x63, 0x6b, 0x88,
	0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c,
	0x48, 0x01, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x88, 0x01, 0x01, 0x42, 0x06, 0x0a, 0x04, 0x5f,
	0x61, 0x63, 0x6b, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x32, 0x7f, 0x0a, 0x0b,
	0x41, 0x63, 0x74, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x30, 0x0a, 0x04, 0x53,
	0x65, 0x6e, 0x64, 0x12, 0x12, 0x2e, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x12, 0x2e, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x12, 0x3e, 0x0a,
	0x09, 0x4f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x19, 0x2e, 0x61, 0x63, 0x74,
	0x73, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x12, 0x2e, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x0b, 0x5a,
	0x09, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_acts_proto_rawDescOnce sync.Once
	file_proto_acts_proto_rawDescData = file_proto_acts_proto_rawDesc
)

func file_proto_acts_proto_rawDescGZIP() []byte {
	file_proto_acts_proto_rawDescOnce.Do(func() {
		file_proto_acts_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_acts_proto_rawDescData)
	})
	return file_proto_acts_proto_rawDescData
}

var file_proto_acts_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_acts_proto_goTypes = []any{
	(*MessageOptions)(nil), // 0: acts.grpc.MessageOptions
	(*Message)(nil),        // 1: acts.grpc.Message
}
var file_proto_acts_proto_depIdxs = []int32{
	1, // 0: acts.grpc.ActsService.Send:input_type -> acts.grpc.Message
	0, // 1: acts.grpc.ActsService.OnMessage:input_type -> acts.grpc.MessageOptions
	1, // 2: acts.grpc.ActsService.Send:output_type -> acts.grpc.Message
	1, // 3: acts.grpc.ActsService.OnMessage:output_type -> acts.grpc.Message
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_acts_proto_init() }
func file_proto_acts_proto_init() {
	if File_proto_acts_proto != nil {
		return
	}
	file_proto_acts_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_acts_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_acts_proto_goTypes,
		DependencyIndexes: file_proto_acts_proto_depIdxs,
		MessageInfos:      file_proto_acts_proto_msgTypes,
	}.Build()
	File_proto_acts_proto = out.File
	file_proto_acts_proto_rawDesc = nil
	file_proto_acts_proto_goTypes = nil
	file_proto_acts_proto_depIdxs = nil
}
